name: Hourly JSON Download

on:
  # 定时触发器（每小时执行一次）
  schedule:
    - cron: '0 * * * *'  # 每小时的第0分钟执行（UTC时间）

  # 手动触发选项（用于调试）
  workflow_dispatch:

jobs:
  download-json:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. 设置下载目录（自动按日期和时间创建）
      - name: Prepare directory
        run: |
          DATETIME=$(date -u +'%Y-%m-%d/%H')
          mkdir -p "./data/$DATETIME"
          echo "DIR_PATH=./data/$DATETIME" >> $GITHUB_ENV

      # 3. 下载 JSON 文件（带错误处理）
      - name: Download JSON data
        run: |
          URL="https://profile-api.hydev.org/exports/hykilp/posts.json"
          curl -sSf "$URL" -o "$DIR_PATH/data.json"
          
          # 验证 JSON 格式
          if ! jq empty "$DIR_PATH/data.json"; then
            echo "❌ Invalid JSON format"
            exit 1
          fi
        env:
          DIR_PATH: ${{ env.DIR_PATH }}

      # 4. 提交更改到仓库
      - name: Commit changes
        run: |
          git config user.name "GitHub JSON Downloader"
          git config user.email "json-downloader@noreply.github.com"
          git add ./data/
          
          # 仅在文件有变化时提交
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Hourly data update: $(date -u +'%Y-%m-%d %H:%M')"
            git push origin main
          fi
